Repository GoogleCloudPlatform/asl-ml-immersion, pull requests merged in 2022-12, with the labels that each got.

#285 updated kfp prebuild pipeline version
  notebooks/kubeflow_pipelines/pipelines/labs/kfp_pipeline_vertex_prebuilt.ipynb
  notebooks/kubeflow_pipelines/pipelines/solutions/kfp_pipeline_vertex_prebuilt.ipynb
  notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_prebuilt.py
Labels: Module Update: 2022/12

#288 Update reinforcement learning module
  .gitignore
  Makefile
  kernels/reinforcement_learning.sh
  notebooks/reinforcement_learning/labs/contextual_bandits_with_tf_agents.ipynb
  notebooks/reinforcement_learning/requirements.txt
  notebooks/reinforcement_learning/solutions/contextual_bandits_with_tf_agents.ipynb
Labels: Module Update: 2022/12

#290 Tf recommenders update
  Makefile
  kernels/tf_recommenders.sh
  notebooks/recommendation_systems/labs/tfrs_basic_retrieval.ipynb
  notebooks/recommendation_systems/solutions/tfrs_basic_retrieval.ipynb
Labels: Module Update: 2022/12

#292 tfx module updates
  notebooks/tfx_pipelines/pipeline/labs/tfx_pipeline_vertex.ipynb
  notebooks/tfx_pipelines/pipeline/solutions/tfx_pipeline_vertex.ipynb
  notebooks/tfx_pipelines/walkthrough/labs/tfx_walkthrough_vertex.ipynb
  notebooks/tfx_pipelines/walkthrough/solutions/tfx_walkthrough_vertex.ipynb
Labels: Module Update: 2022/12

#293 Update xai lab
  notebooks/ml_fairness_explainability/explainable_ai/labs/xai_image_vertex.ipynb
  notebooks/ml_fairness_explainability/explainable_ai/solutions/xai_image_vertex.ipynb
Labels: Module Update: 2022/12

#281 Updated TensorFlow version for TPU - image_models TPU module
  notebooks/image_models/labs/4_tpu_training.ipynb
  notebooks/image_models/solutions/4_tpu_training.ipynb
Labels: Module Update: 2022/12

#280 Updated vertex container - image_models module 2
  notebooks/image_models/labs/2_mnist_models_vertex.ipynb
  notebooks/image_models/solutions/2_mnist_models_vertex.ipynb
Labels: Module Update: 2022/12

#287 Updated `plot_latent_space` function to make it 300x faster in the autoencoder labs
  notebooks/image_models/labs/autoencoder_anomaly_detection.ipynb
  notebooks/image_models/solutions/autoencoder_anomaly_detection.ipynb
Labels: vision

#294 [bug] fix the URL for dataset download in load_text lab
  notebooks/text_models/labs/load_text.ipynb
  notebooks/text_models/solutions/load_text.ipynb
  requirements.txt
Labels: bug

#297 removed what-if tool module
  notebooks/ml_fairness_explainability/inclusive_ml/labs/1_inclusive_ml.ipynb
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/BinX_Choice.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/BinX_Menu.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/BinX_Menu_Choice.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/BinX_Results.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/DemoParityButton.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/DemoParityButton_Resize.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/Features.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/FemaleDemoParity.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/FemaleDemoParitySlider.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/FemaleDetails.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/MaleDemoParity.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/MaleDemoParitySlider.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/MaleDetails.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/PerfTab.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/WIT_25.png
  notebooks/ml_fairness_explainability/inclusive_ml/labs/assets/WIT_Base.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/1_inclusive_ml.ipynb
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/BinX_Choice.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/BinX_Menu.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/BinX_Menu_Choice.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/BinX_Results.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/DemoParityButton.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/DemoParityButton_Resize.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/Features.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/FemaleDemoParity.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/FemaleDemoParitySlider.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/FemaleDetails.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/MaleDemoParity.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/MaleDemoParitySlider.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/MaleDetails.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/PerfTab.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/WIT_25.png
  notebooks/ml_fairness_explainability/inclusive_ml/solution/assets/WIT_Base.png
Labels: Module Update: 2022/12

#298 remove outdated kfp pipeline lab from `building_production_ml_systems`
  notebooks/building_production_ml_systems/assets/taxifare_vertex_pipeline.png
  notebooks/building_production_ml_systems/labs/3_kubeflow_pipelines_vertex.ipynb
  notebooks/building_production_ml_systems/solutions/3_kubeflow_pipelines_vertex.ipynb
Labels: Module Update: 2022/12

#299 adding lab notebook for `solutions/classify_text_with_bert.ipynb`
  notebooks/text_models/labs/classify_text_with_bert.ipynb
Labels: nlp

#301 removed kernel from all goal in Makefile
  Makefile
Labels: Module Update: 2022/12

#304 remove tensorflow-text
  requirements.txt
Labels: bug

#305 adding tf-text to dev_module_update branch
  requirements.txt
Labels: bug

#212 added an optional variational autoencoder lab
  notebooks/image_models/solutions/variational_autoencoder.ipynb
Labels: vision
